# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Latex
version:      2.17
version_from: lib/Template/Latex.pm
installdirs:  site
requires:
    Template:                      2.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
